begin;

-- Realtime chat support and rollup fields used by the app.
alter table public.personal_profiles
  add column if not exists trust_score integer not null default 50;

alter table public.business_profiles
  add column if not exists rating_avg numeric(3, 2) not null default 0,
  add column if not exists trust_score integer not null default 50,
  add column if not exists rating_count integer not null default 0;

alter table public.events
  add column if not exists rating_avg numeric(3, 2) not null default 0,
  add column if not exists rating_count integer not null default 0;

create table if not exists public.event_chats (
  chat_id bigint generated by default as identity primary key,
  event_id bigint not null,
  created_at timestamptz not null default now()
);

alter table public.event_chats
  add column if not exists event_id bigint,
  add column if not exists created_at timestamptz not null default now();

create unique index if not exists event_chats_event_id_key
  on public.event_chats (event_id);

create table if not exists public.chat_messages (
  message_id bigint generated by default as identity primary key,
  chat_id bigint not null,
  sender_user_id uuid not null,
  message_text text,
  sent_at timestamptz not null default now(),
  is_deleted boolean not null default false
);

alter table public.chat_messages
  add column if not exists chat_id bigint,
  add column if not exists sender_user_id uuid,
  add column if not exists message_text text,
  add column if not exists sent_at timestamptz not null default now(),
  add column if not exists is_deleted boolean not null default false;

create index if not exists chat_messages_chat_sent_idx
  on public.chat_messages (chat_id, sent_at);

create table if not exists public.message_reports (
  report_id bigint generated by default as identity primary key,
  message_id bigint not null,
  reporter_user_id uuid not null,
  reason text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.message_reports
  add column if not exists message_id bigint,
  add column if not exists reporter_user_id uuid,
  add column if not exists reason text,
  add column if not exists status text not null default 'pending',
  add column if not exists created_at timestamptz not null default now();

create index if not exists message_reports_message_idx
  on public.message_reports (message_id);

create table if not exists public.payments (
  payment_id bigint generated by default as identity primary key,
  booking_id bigint not null,
  amount numeric(10, 2) not null default 0,
  payment_method text not null default 'card',
  payment_status text not null default 'pending',
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.payments
  add column if not exists booking_id bigint,
  add column if not exists amount numeric(10, 2) not null default 0,
  add column if not exists payment_method text not null default 'card',
  add column if not exists payment_status text not null default 'pending',
  add column if not exists paid_at timestamptz,
  add column if not exists created_at timestamptz not null default now();

create index if not exists payments_booking_idx
  on public.payments (booking_id);

create table if not exists public.reviews (
  review_id bigint generated by default as identity primary key,
  event_id bigint not null,
  reviewer_user_id uuid not null,
  target_user_id uuid,
  target_personal_profile_id bigint,
  target_business_profile_id bigint,
  review_type text not null default 'event',
  stars integer not null,
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reviews
  add column if not exists event_id bigint,
  add column if not exists reviewer_user_id uuid,
  add column if not exists target_user_id uuid,
  add column if not exists target_personal_profile_id bigint,
  add column if not exists target_business_profile_id bigint,
  add column if not exists review_type text not null default 'event',
  add column if not exists stars integer,
  add column if not exists comment text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'reviews_stars_range'
      and conrelid = 'public.reviews'::regclass
  ) then
    alter table public.reviews
      add constraint reviews_stars_range check (stars between 1 and 5);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'reviews_type_check'
      and conrelid = 'public.reviews'::regclass
  ) then
    alter table public.reviews
      add constraint reviews_type_check
      check (review_type in ('event', 'organizer', 'participant', 'personal', 'business'));
  end if;
end
$$;

create unique index if not exists reviews_one_target_per_event
  on public.reviews (event_id, reviewer_user_id, target_user_id, review_type);

create index if not exists reviews_target_user_idx
  on public.reviews (target_user_id, created_at desc);

create index if not exists reviews_event_idx
  on public.reviews (event_id, created_at desc);

update public.reviews r
set target_user_id = p.user_id
from public.personal_profiles p
where r.target_user_id is null
  and r.target_personal_profile_id = p.profile_id;

update public.reviews r
set target_user_id = b.user_id
from public.business_profiles b
where r.target_user_id is null
  and r.target_business_profile_id = b.business_profile_id;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reviews_set_updated_at on public.reviews;
create trigger reviews_set_updated_at
before update on public.reviews
for each row execute function public.set_updated_at();

create or replace function public.calculate_user_trust_score(p_user_id uuid)
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_avg_stars numeric := 3;
  v_review_count integer := 0;
  v_attended_count integer := 0;
  v_hosted_count integer := 0;
  v_report_count integer := 0;
  v_review_component numeric := 0;
  v_score numeric := 50;
begin
  if p_user_id is null then
    return 0;
  end if;

  select coalesce(avg(stars), 3), count(*)
    into v_avg_stars, v_review_count
  from public.reviews
  where target_user_id = p_user_id;

  select count(*)
    into v_attended_count
  from public.bookings b
  join public.events e on e.event_id = b.event_id
  where b.user_id = p_user_id
    and b.booking_status = 'confirmed'
    and e.end_datetime < now();

  select count(*)
    into v_hosted_count
  from public.events e
  where e.organizer_user_id = p_user_id
    and e.end_datetime < now()
    and coalesce(e.status, 'published') <> 'cancelled';

  select count(*)
    into v_report_count
  from public.message_reports mr
  join public.chat_messages cm on cm.message_id = mr.message_id
  where cm.sender_user_id = p_user_id
    and mr.status in ('pending', 'confirmed', 'resolved');

  v_review_component := ((v_avg_stars - 3) * 10) + least(10, v_review_count * 2);
  v_score := 50
    + least(25, greatest(-25, v_review_component))
    + least(15, v_attended_count * 2)
    + least(15, v_hosted_count * 3)
    - least(20, v_report_count * 4);

  return greatest(0, least(100, round(v_score)))::integer;
end;
$$;

create or replace function public.refresh_user_trust_score(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_score integer := 0;
  v_avg numeric := 0;
  v_count integer := 0;
begin
  if p_user_id is null then
    return 0;
  end if;

  v_score := public.calculate_user_trust_score(p_user_id);

  update public.personal_profiles
    set trust_score = v_score
  where user_id = p_user_id;

  select coalesce(avg(stars), 0), count(*)
    into v_avg, v_count
  from public.reviews
  where target_user_id = p_user_id;

  update public.business_profiles
    set trust_score = v_score,
        rating_avg = round(v_avg, 2),
        rating_count = v_count
  where user_id = p_user_id;

  return v_score;
end;
$$;

create or replace function public.refresh_event_rating(p_event_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_avg numeric := 0;
  v_count integer := 0;
begin
  if p_event_id is null then
    return;
  end if;

  select coalesce(avg(stars), 0), count(*)
    into v_avg, v_count
  from public.reviews
  where event_id = p_event_id;

  update public.events
    set rating_avg = round(v_avg, 2),
        rating_count = v_count
  where event_id = p_event_id;
end;
$$;

create or replace function public.handle_review_rollups()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op in ('INSERT', 'UPDATE') then
    perform public.refresh_user_trust_score(new.target_user_id);
    perform public.refresh_event_rating(new.event_id);
  end if;

  if tg_op in ('UPDATE', 'DELETE') then
    perform public.refresh_user_trust_score(old.target_user_id);
    perform public.refresh_event_rating(old.event_id);
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists reviews_refresh_rollups on public.reviews;
create trigger reviews_refresh_rollups
after insert or update or delete on public.reviews
for each row execute function public.handle_review_rollups();

create or replace function public.handle_booking_trust_refresh()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op in ('INSERT', 'UPDATE') then
    perform public.refresh_user_trust_score(new.user_id);
  end if;

  if tg_op in ('UPDATE', 'DELETE') then
    perform public.refresh_user_trust_score(old.user_id);
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists bookings_refresh_trust_score on public.bookings;
create trigger bookings_refresh_trust_score
after insert or update or delete on public.bookings
for each row execute function public.handle_booking_trust_refresh();

create or replace function public.handle_event_trust_refresh()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op in ('INSERT', 'UPDATE') then
    perform public.refresh_user_trust_score(new.organizer_user_id);
    perform public.refresh_event_rating(new.event_id);
  end if;

  if tg_op in ('UPDATE', 'DELETE') then
    perform public.refresh_user_trust_score(old.organizer_user_id);
    perform public.refresh_event_rating(old.event_id);
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists events_refresh_trust_score on public.events;
create trigger events_refresh_trust_score
after insert or update or delete on public.events
for each row execute function public.handle_event_trust_refresh();

create or replace function public.ensure_event_chat()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.event_chats (event_id)
  values (new.event_id)
  on conflict (event_id) do nothing;

  return new;
end;
$$;

drop trigger if exists events_ensure_event_chat on public.events;
create trigger events_ensure_event_chat
after insert on public.events
for each row execute function public.ensure_event_chat();

create or replace function public.cleanup_event_dependents()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_chat_ids bigint[];
  v_booking_ids bigint[];
begin
  select array_agg(chat_id::bigint)
    into v_chat_ids
  from public.event_chats
  where event_id = old.event_id;

  select array_agg(booking_id::bigint)
    into v_booking_ids
  from public.bookings
  where event_id = old.event_id;

  delete from public.payments
  where booking_id = any(v_booking_ids);

  delete from public.reviews
  where event_id = old.event_id;

  delete from public.message_reports
  where message_id in (
    select message_id
    from public.chat_messages
    where chat_id = any(v_chat_ids)
  );

  delete from public.chat_messages
  where chat_id = any(v_chat_ids);

  delete from public.event_chats
  where event_id = old.event_id;

  delete from public.event_tags
  where event_id = old.event_id;

  delete from public.bookings
  where event_id = old.event_id;

  return old;
end;
$$;

drop trigger if exists events_cleanup_dependents on public.events;
create trigger events_cleanup_dependents
before delete on public.events
for each row execute function public.cleanup_event_dependents();

insert into public.event_chats (event_id)
select e.event_id
from public.events e
left join public.event_chats c on c.event_id = e.event_id
where c.chat_id is null
on conflict (event_id) do nothing;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'chat_messages'
    ) then
      alter publication supabase_realtime add table public.chat_messages;
    end if;
  end if;
end
$$;

alter table public.chat_messages replica identity full;

alter table public.reviews enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'reviews_select_authenticated'
  ) then
    create policy reviews_select_authenticated
      on public.reviews for select
      to authenticated
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'reviews_insert_own'
  ) then
    create policy reviews_insert_own
      on public.reviews for insert
      to authenticated
      with check (
        reviewer_user_id = auth.uid()
        and (target_user_id is null or target_user_id <> auth.uid())
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'reviews_update_own'
  ) then
    create policy reviews_update_own
      on public.reviews for update
      to authenticated
      using (reviewer_user_id = auth.uid())
      with check (reviewer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'reviews_delete_own'
  ) then
    create policy reviews_delete_own
      on public.reviews for delete
      to authenticated
      using (reviewer_user_id = auth.uid());
  end if;
end
$$;

create or replace function public.delete_current_user()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_personal_profile_ids bigint[];
  v_business_profile_ids bigint[];
  v_event_ids bigint[];
  v_chat_ids bigint[];
  v_booking_ids bigint[];
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select array_agg(profile_id::bigint)
    into v_personal_profile_ids
  from public.personal_profiles
  where user_id = v_user_id;

  select array_agg(business_profile_id::bigint)
    into v_business_profile_ids
  from public.business_profiles
  where user_id = v_user_id;

  select array_agg(event_id::bigint)
    into v_event_ids
  from public.events
  where organizer_user_id = v_user_id;

  select array_agg(chat_id::bigint)
    into v_chat_ids
  from public.event_chats
  where event_id = any(v_event_ids);

  select array_agg(booking_id::bigint)
    into v_booking_ids
  from public.bookings
  where user_id = v_user_id
     or event_id = any(v_event_ids);

  delete from public.payments
  where booking_id = any(v_booking_ids);

  delete from public.reviews
  where reviewer_user_id = v_user_id
     or target_user_id = v_user_id
     or target_personal_profile_id = any(v_personal_profile_ids)
     or target_business_profile_id = any(v_business_profile_ids)
     or event_id = any(v_event_ids);

  delete from public.message_reports
  where reporter_user_id = v_user_id
     or message_id in (
       select message_id
       from public.chat_messages
       where sender_user_id = v_user_id
          or chat_id = any(v_chat_ids)
     );

  delete from public.chat_messages
  where sender_user_id = v_user_id
     or chat_id = any(v_chat_ids);

  delete from public.event_chats
  where event_id = any(v_event_ids);

  delete from public.event_tags
  where event_id = any(v_event_ids);

  delete from public.bookings
  where user_id = v_user_id
     or event_id = any(v_event_ids);

  delete from public.events
  where organizer_user_id = v_user_id;

  delete from public.personal_profiles
  where user_id = v_user_id;

  delete from public.business_profiles
  where user_id = v_user_id;

  delete from public.users
  where user_id = v_user_id;

  delete from auth.users
  where id = v_user_id;
end;
$$;

grant execute on function public.calculate_user_trust_score(uuid) to authenticated;
grant execute on function public.refresh_user_trust_score(uuid) to authenticated;
grant execute on function public.delete_current_user() to authenticated;

do $$
declare
  r record;
begin
  for r in select user_id from public.users loop
    perform public.refresh_user_trust_score(r.user_id);
  end loop;
end
$$;

commit;
