begin;

create table if not exists public.users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  phone text,
  account_type text not null default 'personal',
  role text not null default 'user',
  account_status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_account_type_check check (account_type in ('personal', 'business')),
  constraint users_role_check check (role in ('user', 'admin', 'moderator')),
  constraint users_account_status_check check (account_status in ('active', 'suspended', 'deleted'))
);

create table if not exists public.personal_profiles (
  profile_id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users (user_id) on delete cascade,
  full_name text not null,
  date_of_birth date,
  gender text,
  photo_url text,
  trust_score integer not null default 50,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint personal_profiles_trust_score_range check (trust_score between 0 and 100)
);

create table if not exists public.business_profiles (
  business_profile_id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users (user_id) on delete cascade,
  business_name text not null,
  business_category text not null,
  short_description text not null,
  contact_person_name text not null,
  logo_url text,
  location_text text,
  website text,
  social_media_link text,
  rating_avg numeric(3, 2) not null default 0,
  rating_count integer not null default 0,
  trust_score integer not null default 50,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint business_profiles_rating_avg_range check (rating_avg between 0 and 5),
  constraint business_profiles_rating_count_nonnegative check (rating_count >= 0),
  constraint business_profiles_trust_score_range check (trust_score between 0 and 100)
);

create table if not exists public.tags (
  tag_id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.events (
  event_id bigint generated by default as identity primary key,
  organizer_user_id uuid not null references public.users (user_id) on delete cascade,
  title text not null,
  description text not null,
  cover_image_url text,
  start_datetime timestamptz not null,
  end_datetime timestamptz not null,
  location_text text not null,
  latitude double precision,
  longitude double precision,
  max_participants integer not null,
  pricing_model text not null default 'free',
  ticket_price numeric(10, 2),
  status text not null default 'published',
  rating_avg numeric(3, 2) not null default 0,
  rating_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint events_title_length check (char_length(btrim(title)) between 3 and 100),
  constraint events_description_length check (char_length(btrim(description)) between 1 and 1000),
  constraint events_time_order check (end_datetime > start_datetime),
  constraint events_capacity_positive check (max_participants > 0),
  constraint events_pricing_model_check check (pricing_model in ('free', 'paid')),
  constraint events_ticket_price_check check (
    (pricing_model = 'free' and ticket_price is null)
    or (pricing_model = 'paid' and ticket_price is not null and ticket_price > 0)
  ),
  constraint events_status_check check (status in ('draft', 'published', 'cancelled')),
  constraint events_latitude_range check (latitude is null or latitude between -85 and 85),
  constraint events_longitude_range check (longitude is null or longitude between -180 and 180),
  constraint events_rating_avg_range check (rating_avg between 0 and 5),
  constraint events_rating_count_nonnegative check (rating_count >= 0)
);

create table if not exists public.event_tags (
  event_id bigint not null references public.events (event_id) on delete cascade,
  tag_id bigint not null references public.tags (tag_id) on delete restrict,
  primary key (event_id, tag_id)
);

create table if not exists public.bookings (
  booking_id bigint generated by default as identity primary key,
  event_id bigint not null references public.events (event_id) on delete cascade,
  user_id uuid not null references public.users (user_id) on delete cascade,
  booking_status text not null default 'pending',
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_one_per_user_event unique (event_id, user_id),
  constraint bookings_status_check check (booking_status in ('pending', 'confirmed', 'cancelled'))
);

create index if not exists events_organizer_idx
  on public.events (organizer_user_id, start_datetime desc);

create index if not exists events_status_start_idx
  on public.events (status, start_datetime);

create index if not exists bookings_event_status_idx
  on public.bookings (event_id, booking_status);

create index if not exists bookings_user_joined_idx
  on public.bookings (user_id, joined_at desc);

insert into public.tags (name)
values
  ('Arts'),
  ('Business'),
  ('Community'),
  ('Education'),
  ('Food'),
  ('Games'),
  ('Music'),
  ('Networking'),
  ('Outdoors'),
  ('Sports'),
  ('Technology'),
  ('Wellness')
on conflict (name) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists personal_profiles_set_updated_at on public.personal_profiles;
create trigger personal_profiles_set_updated_at
before update on public.personal_profiles
for each row execute function public.set_updated_at();

drop trigger if exists business_profiles_set_updated_at on public.business_profiles;
create trigger business_profiles_set_updated_at
before update on public.business_profiles
for each row execute function public.set_updated_at();

drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at
before update on public.events
for each row execute function public.set_updated_at();

drop trigger if exists bookings_set_updated_at on public.bookings;
create trigger bookings_set_updated_at
before update on public.bookings
for each row execute function public.set_updated_at();

create or replace function public.validate_booking()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event record;
  v_active_count integer := 0;
begin
  if new.booking_status not in ('pending', 'confirmed') then
    return new;
  end if;

  select event_id, organizer_user_id, max_participants, start_datetime, status
    into v_event
  from public.events
  where event_id = new.event_id;

  if not found then
    raise exception 'Event not found';
  end if;

  if v_event.organizer_user_id = new.user_id then
    raise exception 'Organizers cannot book their own event';
  end if;

  if v_event.status <> 'published' then
    raise exception 'Event is not available for booking';
  end if;

  if v_event.start_datetime <= now() then
    raise exception 'Event has already started';
  end if;

  select count(*)
    into v_active_count
  from public.bookings b
  where b.event_id = new.event_id
    and b.booking_status in ('pending', 'confirmed')
    and (tg_op = 'INSERT' or b.booking_id <> new.booking_id);

  if v_active_count >= v_event.max_participants then
    raise exception 'Event is full';
  end if;

  return new;
end;
$$;

drop trigger if exists bookings_validate_before_write on public.bookings;
create trigger bookings_validate_before_write
before insert or update on public.bookings
for each row execute function public.validate_booking();

alter table public.users enable row level security;
alter table public.personal_profiles enable row level security;
alter table public.business_profiles enable row level security;
alter table public.tags enable row level security;
alter table public.events enable row level security;
alter table public.event_tags enable row level security;
alter table public.bookings enable row level security;

drop policy if exists users_select_own on public.users;
create policy users_select_own
  on public.users for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists users_insert_own on public.users;
create policy users_insert_own
  on public.users for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists users_update_own on public.users;
create policy users_update_own
  on public.users for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists personal_profiles_select_authenticated on public.personal_profiles;
create policy personal_profiles_select_authenticated
  on public.personal_profiles for select
  to authenticated
  using (true);

drop policy if exists personal_profiles_insert_own on public.personal_profiles;
create policy personal_profiles_insert_own
  on public.personal_profiles for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists personal_profiles_update_own on public.personal_profiles;
create policy personal_profiles_update_own
  on public.personal_profiles for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists business_profiles_select_authenticated on public.business_profiles;
create policy business_profiles_select_authenticated
  on public.business_profiles for select
  to authenticated
  using (true);

drop policy if exists business_profiles_insert_own on public.business_profiles;
create policy business_profiles_insert_own
  on public.business_profiles for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists business_profiles_update_own on public.business_profiles;
create policy business_profiles_update_own
  on public.business_profiles for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists tags_select_authenticated on public.tags;
create policy tags_select_authenticated
  on public.tags for select
  to authenticated
  using (true);

drop policy if exists events_select_available on public.events;
create policy events_select_available
  on public.events for select
  to authenticated
  using (status = 'published' or organizer_user_id = auth.uid());

drop policy if exists events_insert_own on public.events;
create policy events_insert_own
  on public.events for insert
  to authenticated
  with check (organizer_user_id = auth.uid());

drop policy if exists events_update_own on public.events;
create policy events_update_own
  on public.events for update
  to authenticated
  using (organizer_user_id = auth.uid())
  with check (organizer_user_id = auth.uid());

drop policy if exists events_delete_own on public.events;
create policy events_delete_own
  on public.events for delete
  to authenticated
  using (organizer_user_id = auth.uid());

drop policy if exists event_tags_select_available on public.event_tags;
create policy event_tags_select_available
  on public.event_tags for select
  to authenticated
  using (
    exists (
      select 1
      from public.events e
      where e.event_id = event_tags.event_id
        and (e.status = 'published' or e.organizer_user_id = auth.uid())
    )
  );

drop policy if exists event_tags_insert_organizer on public.event_tags;
create policy event_tags_insert_organizer
  on public.event_tags for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.events e
      where e.event_id = event_tags.event_id
        and e.organizer_user_id = auth.uid()
    )
  );

drop policy if exists event_tags_delete_organizer on public.event_tags;
create policy event_tags_delete_organizer
  on public.event_tags for delete
  to authenticated
  using (
    exists (
      select 1
      from public.events e
      where e.event_id = event_tags.event_id
        and e.organizer_user_id = auth.uid()
    )
  );

drop policy if exists bookings_select_authenticated on public.bookings;
create policy bookings_select_authenticated
  on public.bookings for select
  to authenticated
  using (true);

drop policy if exists bookings_insert_own on public.bookings;
create policy bookings_insert_own
  on public.bookings for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.events e
      where e.event_id = bookings.event_id
        and e.organizer_user_id <> auth.uid()
        and e.status = 'published'
    )
  );

drop policy if exists bookings_update_own_or_organizer on public.bookings;
create policy bookings_update_own_or_organizer
  on public.bookings for update
  to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1
      from public.events e
      where e.event_id = bookings.event_id
        and e.organizer_user_id = auth.uid()
    )
  )
  with check (
    user_id = auth.uid()
    or exists (
      select 1
      from public.events e
      where e.event_id = bookings.event_id
        and e.organizer_user_id = auth.uid()
    )
  );

drop policy if exists bookings_delete_own_or_organizer on public.bookings;
create policy bookings_delete_own_or_organizer
  on public.bookings for delete
  to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1
      from public.events e
      where e.event_id = bookings.event_id
        and e.organizer_user_id = auth.uid()
    )
  );

commit;
